# Default values for argocd-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

argocd:
  namespace: argocd
  service:
    name: argocd-svc
    port: 80
    targetPort: 8080
          

ingress:
  argocd:
    name: argocd-ingress
    namespace: argocd
    annotations:
      certificatearn: "arn:aws:acm:ap-northeast-2:261595668962:certificate/fc29e6b8-016a-4b56-a413-70e7262fa16d"
    host: "argocd.jm.busan.kr"
    path: "/"
    backend:
      service:
        name: "argocd-svc"
        port: 80



