argocd:
  namespace: argocd
  service:
    name: argocd-svc
    port: 80
    targetPort: 8080
    
application:
  name: "was"
  namespace: "argocd"
  destination:
    namespace: "default"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    path: "was"
    repoURL: "https://github.com/claire-eee/meju-test.git"
    targetRevision: "HEAD"
    kustomize:
      namespace: "default"
  syncPolicy:
    automated:
      selfHeal: true

          

ingress:
  argocd:
    name: argocd-ingress
    namespace: argocd
    annotations:
      certificatearn: "arn:aws:acm:ap-northeast-2:213315937280:certificate/9474e958-da64-4988-a048-4c8283bb3823"
    host: "argocd.claire.directory"
    path: "/"
    backend:
      service:
        name: "argocd-svc"
        port: 80