apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: argocd-server-patch-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-server-patch-rolebinding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: default
  namespace: argocd
roleRef:
  kind: Role
  name: argocd-server-patch-role
  apiGroup: rbac.authorization.k8s.io
