apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.argocd.service.name }}
  namespace: {{ .Values.argocd.namespace }}
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - port: {{ .Values.argocd.service.port }}
      targetPort: {{ .Values.argocd.service.targetPort }}
  type: NodePort
