apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.argocd.name }}
  namespace: {{ .Values.ingress.argocd.namespace }}
  annotations:
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.argocd.annotations.targetType }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.argocd.annotations.scheme }}
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.ingress.argocd.annotations.listenPorts }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.argocd.annotations.certificateArn }}
    alb.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.argocd.annotations.sslRedirect }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.ingress.argocd.annotations.healthcheckPath }}
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ .Values.ingress.argocd.annotations.healthcheckProtocol }}
    alb.ingress.kubernetes.io/success-codes: {{ .Values.ingress.argocd.annotations.successCodes }}
spec:
  ingressClassName: {{ .Values.ingress.argocd.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.argocd.host }}
      http:
        paths:
          - path: {{ .Values.ingress.argocd.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.argocd.backend.service.name }}
                port:
                  number: {{ .Values.ingress.argocd.backend.service.port }}
