apiVersion: batch/v1
kind: Job
metadata:
  name: patch-argocd-server-post-install
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: kubectl-patch
        image: bitnami/kubectl:latest
        command: ["kubectl", "patch", "deployment", "argocd-server", "--namespace", "argocd", "--type", "json", "--patch", "$(cat /patch/patch.json)"]
        volumeMounts:
        - name: patch-volume
          mountPath: /patch
      restartPolicy: Never
      volumes:
      - name: patch-volume
        configMap:
          name: argocd-server-patch
          items:
          - key: patch.json
            path: patch.json
